[package]
name = "rosie"
version = "0.1.0"
edition = "2021"

[dependencies]
rlua = "0.19.4"
serde = { version = "1.0.163", features = ["derive"] }
toml = "0.7.4"
wav = "1.0.0"
whisper = { path = "../whisper" }
